# IMPORTS
import os
import sys
import subprocess
import tomllib
import argparse

# HELPER FUNCTIONS
def find_toml() -> dict:
    toml_path = os.path.join(os.getcwd(), "cask.toml")
    if not os.path.exists(toml_path):
        print("Error: No cask.toml found in current directory.")
        sys.exit(1)
    with open(toml_path, "rb") as f:
        return tomllib.load(f)

def validate_toml(config: dict) -> None:
    app = config.get("app", {})
    if not app.get("name"):
        print("Error: cask.toml missing [app] name")
        sys.exit(1)
    if not app.get("entry"):
        print("Error: cask.toml missing [app] entry")
        sys.exit(1)
    if not os.path.exists(app["entry"]):
        print(f"Error: entry file '{app['entry']}' not found")
        sys.exit(1)

def build_pyinstaller_cmd(config: dict, args: argparse.Namespace) -> list[str]:
    app = config.get("app", {})
    data = config.get("data", {})

    cmd = [
        "pyinstaller",
        "--windowed",
        "--noconfirm",
        "--name", app["name"],
        "--paths", ".",
    ]

    if app.get("icon"):
        cmd += ["--icon", app["icon"]]

    if args.onefile:
        cmd.append("--onefile")

    path_seperator = ";" if sys.platform == "win32" else ":"
    for source, dest in data.items():
        cmd += ["--add-data", f"{source}{path_seperator}{dest}"]

    cmd.append(app["entry"])
    return cmd

def cmd_build(args: argparse.Namespace) -> None:
    config = find_toml()
    validate_toml(config)
    cmd = build_pyinstaller_cmd(config, args)
    subprocess.run(cmd)

def discover_defaults() -> dict:
    """Scan current directory for common Flask project files."""
    
    # App name from directory
    app_name = os.path.basename(os.getcwd()).replace("-", " ").replace("_", " ").title()

    # Entry file
    entry = next((f for f in ["main.py", "app.py", "run.py"] if os.path.isfile(f)), "")

    # Icon
    icon = next((f for f in [
        "static/favicon.ico", "static/icon.ico", "static/icon.png"
    ] if os.path.isfile(f)), "")

    # Data folders
    data = []
    for folder in ["static", "templates", "assets"]:
        if os.path.isdir(folder):
            data.append(folder)
    # Only include instance if it has files
    if os.path.isdir("instance") and os.listdir("instance"):
        data.append("instance")

    return {"app_name": app_name, "entry": entry, "icon": icon, "data": data}


def generate_toml(app_name: str, entry: str, icon: str, data: list[str]) -> str:
    """Generate cask.toml content as a string."""
    lines = [
        "# Generated by cask init",
        "[app]",
        f'name = "{app_name}"',
        f'entry = "{entry}"',
    ]
    if icon:
        lines.append(f'icon = "{icon}"')
    lines.append("")

    if data:
        lines.append("[data]")
        for folder in data:
            lines.append(f'"{folder}" = "{folder}"')
        lines.append("")

    return "\n".join(lines)

def cmd_init(args) -> None:
    defaults = discover_defaults()
    toml_exists = os.path.isfile("cask.toml")
    content = ""

    if not args.interactive:
        if toml_exists and not args.force:
            print("Error: cask.toml already exists. Use --force to overwrite.")
            sys.exit(1)

        print("Discovered:")
        print(f"  app name:  {defaults['app_name']}")
        print(f"  entry:     {defaults['entry'] or '(none found)'}")
        print(f"  icon:      {defaults['icon'] or '(none found)'}")
        print(f"  data:      {', '.join(f'{d}/' for d in defaults['data']) or '(none found)'}")
        print()

        content = generate_toml(
            defaults["app_name"], defaults["entry"],
            defaults["icon"], defaults["data"]
        )

    else:
        print("Interactive Mode:")
        print("Press enter to use the [Suggested value], or enter your own value")
        app_name = input(f"App name [{defaults['app_name']}]: ").strip() or defaults["app_name"]
        entry    = input(f"Entry file [{defaults['entry'] or 'main.py'}]: ").strip() or defaults["entry"] or "main.py"
        icon     = input(f"Icon [{defaults['icon'] or 'none'}]: ").strip() or defaults["icon"]
        
        default_data_str = ", ".join(f"{d}/" for d in defaults["data"]) or "none"
        data_input = input(f"Data folders [{default_data_str}]: ").strip()
        if data_input:
            data = [d.strip().rstrip("/") for d in data_input.split(",") if d.strip()]
        else:
            data = defaults["data"]

        content = generate_toml(app_name, entry, icon, data)

        if toml_exists and not args.force:
            answer = input("\ncask.toml already exists. Overwrite? [y/N]: ").strip().lower()
            if answer != "y":
                print("\nPreview of generated cask.toml:")
                print("--------------------------------")
                print(content)
                return

    with open("cask.toml", "w") as f:
        f.write(content)
    print("Generated cask.toml!")

# MAIN FUNCTION
def main() -> None:
    parser = argparse.ArgumentParser(prog="cask", description="Cask - Flask app packager")
    subparsers = parser.add_subparsers(dest="command")

    # Command: build
    build_parser = subparsers.add_parser("build", help="Package the app using cask.toml")
    build_parser.add_argument("--onefile", action="store_true", help="Package app as a single binary")

    # Command: init
    init_parser = subparsers.add_parser("init", help="Generate a cask.toml for this project")
    init_parser.add_argument("-i", "--interactive", action="store_true", help="Interactive mode for guidance")
    init_parser.add_argument("--force", action="store_true", help="Force creates cask.toml file, overwrites existing cask.toml")

    args = parser.parse_args()

    if args.command == "build":
        cmd_build(args)
    elif args.command == "init":
        cmd_init(args)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()